# Generated by Django 2.2.4 on 2020-12-02 12:38

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('taskdiscretion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='po_check',
            field=otree.db.models.IntegerField(choices=[[1, 'Helemaal oneens'], [2, 'Oneens'], [3, 'Beetje mee oneens'], [4, 'Noch mee oneens, noch mee eens'], [5, 'Beetje mee eens'], [6, 'Eens'], [7, 'Helemaal eens']], null=True, verbose_name='Het documenteren beschouw ik als een onderdeel van de audit taken.'),
        ),
    ]
