# Generated by Django 2.2.4 on 2021-05-21 11:15

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('taskdiscretion_eng', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='pom_3_4',
            field=otree.db.models.IntegerField(choices=[[1, 'Disagree strongly'], [2, 'Disagree moderately'], [3, 'Disagree slightly'], [4, 'Neither agree nor disagree'], [5, 'Agree slightly'], [6, 'Agree moderately'], [7, 'Agree strongly']], null=True, verbose_name='When I conducted the audit tasks, I experienced time pressure.'),
        ),
    ]
