# Generated by Django 2.2.4 on 2021-05-21 11:22

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('taskdiscretion_eng', '0002_auto_20210521_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='need_for_cognition_3',
            field=otree.db.models.IntegerField(choices=[[1, 'Disagree strongly'], [2, 'Disagree moderately'], [3, 'Disagree slightly'], [4, 'Neither agree nor disagree'], [5, 'Agree slightly'], [6, 'Agree moderately'], [7, 'Agree strongly']], null=True, verbose_name='I am proud of the outcomes of my reasoning.'),
        ),
    ]
